services:
  backend:
    build: .
    container_name: backend
    tty: true
    stdin_open: true
    ports:
      - 3333:3333
    volumes:
      - ./:/app
    environment:
      - TZ=UTC
      - NODE_ENV=development
      - PORT=3333
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - APP_KEY=DGFvXF6d4SmvJHSMIx4WFCPZ6N8asozn
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=userpassword
      - DB_DATABASE=store_db
      - JWT_SECRET= secretJWT
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=store_db
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=userpassword
      - MYSQL_PASSWORD=userpassword